# Generated by Django 4.0 on 2021-12-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('estilo', models.DateField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloCaracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantPersonas', models.IntegerField()),
                ('caracteristica', models.CharField(max_length=30)),
                ('ejes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clasificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terreno', models.CharField(max_length=30)),
                ('kilometros', models.IntegerField()),
                ('duenios', models.IntegerField()),
            ],
        ),
    ]
