# Generated by Django 4.0 on 2021-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificaciones',
            name='terreno',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='estilo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
